#!/bin/bash

rsync --exclude .plexignore --exclude _un --times --size-only -r -av /mnt/HD/HD_a2/Media/Downloads/ /mnt/USB/USB2_d2/Downloads/
rsync --exclude .plexignore --exclude _un -r -av /mnt/HD/HD_a2/Media/Downloads/ /mnt/USB/USB2_d2/Downloads/
