#!/bin/bash

rsync --exclude .plexignore --times --size-only -r -av --progress /mnt/md0/media/Downloads/ /mnt/usb/usbshare2/Downloads/
rsync --exclude .plexignore -r -av --progress /mnt/md0/media/Downloads/ /mnt/usb/usbshare2/Downloads/
