#!/bin/bash

rsync --exclude .plexignore --times --size-only -r -av --progress /mnt/md0/media/Movies/ /mnt/usb/usbshare2/Movies/
rsync --exclude .plexignore -r --progress /mnt/md0/media/Movies/ /mnt/usb/usbshare2/Movies/
