#!/bin/bash

rsync --exclude .plexignore --times --size-only -r -av --progress /mnt/md0/media/TV/ /mnt/usb/usbshare2/TV/
rsync --exclude .plexignore -r -av --progress /mnt/md0/media/TV/ /mnt/usb/usbshare2/TV/
