#!/bin/bash

for D in /mnt/usb/usbshare2/Downloads/*; do
    if [ -d "${D}" ]; then
        echo "${D}"   # your processing here
        NAME=$(basename "${D}")

        rsync --delete --times --size-only -r -av --progress "/mnt/md0/media/Downloads/${NAME}/" "${D}/"
        rsync --delete -r -av --progress "/mnt/md0/media/Downloads/${NAME}/" "${D}/"
    fi
done

for D in /mnt/usb/usbshare2/TV/*; do
    if [ -d "${D}" ]; then
        echo "${D}"   # your processing here
        NAME=$(basename "${D}")

        rsync --delete --times --size-only -r -av --progress "/mnt/md0/media/TV/${NAME}/" "${D}/"
        rsync --delete -r -av --progress "/mnt/md0/media/TV/${NAME}/" "${D}/"
    fi
done
