Vagrant.configure('2') do |config|
    # Enable caching
    if Vagrant.has_plugin?('vagrant-cachier')
        config.cache.scope = :box

        config.cache.synced_folder_opts = {
            type: :nfs,
            mount_options: ['rw', 'vers=3', 'tcp', 'nolock']
        }
    end

    # Use vagrant SSH
    config.ssh.ssh_command = 'sshrc'
end
