require 'socket'

Vagrant.configure('2') do |config|
    # Enable caching
    if Vagrant.has_plugin?('vagrant-cachier')
        config.cache.scope = :box

        config.cache.synced_folder_opts = {
            type: :nfs,
            mount_options: ['rw', 'vers=3', 'tcp', 'nolock']
        }
    end

    # Use sshrc instead of normal SSH
    config.ssh.ssh_command = 'sshrc'

    # Set the hostname to the folder name if one isn't set
    config.vm.hostname = getHostName()

    config.vm.provider :virtualbox do |provider|

        if isIssaMachine()
            provider.customize ["modifyvm", :id, "--groups", "/Services"]
        end

        if config.vm.box == 'ubuntu/trusty64'
            provider.customize ["modifyvm", :id, "--ostype", "Ubuntu_64"]
        end
    end
end

# Set the hostname of machine to the hostname of the host + the folder name if they aren't explictly set
def getHostName()
    folder = File.basename(Dir.getwd)

    return Socket.gethostname + '-' + folder.gsub('_', '-')
end

# Set work machines into a group
def isIssaMachine()
    if Dir.getwd.include? "services-dev"
        return true
    end

    return false
end
